config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/adim:
      branch: main
      repo: https://github.com/grycap/adim.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/adim git:
        commands:
        - /usr/bin/env sh .sqa/script.persimmon_vibrant_pegasus.sh
        container: qc.acc_chili_hopeful_armadillo
  QC.Doc:
    repos:
      github.com/grycap/adim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.porcelain_sociable_newt.sh
        container: qc.doc_puce_balanced_stingray
      github.com/grycap/adim git:
        commands:
        - /usr/bin/env sh .sqa/script.pistachio_cranky_penguin.sh
        container: qc.doc_fern_balanced_turtle
      github.com/grycap/adim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.polar_romantic_sphinx.sh
        container: qc.doc_marigold_perceptive_komodo
  QC.Lic:
    repos:
      github.com/grycap/adim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.linen_helpful_alpaca.sh
        container: qc.lic_turmeric_perky_quoll
  QC.Met:
    repos:
      github.com/grycap/adim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.tan_adaptable_clownfish.sh
        container: qc.met_malachite_balanced_orangutan
  QC.Sec:
    repos:
      github.com/grycap/adim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.reef_sympathetic_alpaca.sh
        container: qc.sec_sepia_outgoing_jellyfish
  QC.Sty:
    repos:
      github.com/grycap/adim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.coffee_anxious_octopus.sh
        container: qc.sty_gamboge_unique_hare
      github.com/grycap/adim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tan_artistic_ibex.sh
        container: qc.sty_byzantium_decisive_gnu
      github.com/grycap/adim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lapis_careful_parrot.sh
        container: qc.sty_beige_innocent_mink
  QC.Uni:
    repos:
      github.com/grycap/adim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.green_spontaneous_gerbil.sh
        container: qc.uni_bone_articulate_gerbil
  QC.Ver:
    repos:
      github.com/grycap/adim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zinnia_confused_kiwi.sh
        container: qc.ver_bronze_pensive_echidna
timeout: 5400
